- hosts: learning-neo4j-node1
  become: yes
  remote_user: learning
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ neo4j_backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ neo4j_backup_azure_storage_access_key }}"
  roles:
        - neo4j-backup 
