---
#tasks file for deployartifact

- name: stop tomcat
  service: name=tomcat state=stopped


- name: copy the database.properties
  template: src=language/database.properties.j2 dest=/data/properties/language/database.properties

- name: copy the graph.properties
  template: src=language/graph.properties.j2 dest=/data/properties/language/graph.properties


- name: copy the language-indexes.properties
  template: src=language/language-indexes.properties.j2 dest=/data/properties/language/language-indexes.properties


- name: copy the mongo.properties
  template: src=language/mongo.properties.j2 dest=/data/properties/language/mongo.properties

#------------------------------------------------------------------------------------

- name: copy the consumer-config.xml
  template: src=learning/consumer-config.xml.j2 dest=/data/properties/learning/consumer-config.xml

- name: copy the database.properties
  template: src=learning/database.properties.j2 dest=/data/properties/learning/database.properties

- name: copy the elasticsearch.properties
  template: src=learning/elasticsearch.properties.j2 dest=/data/properties/learning/elasticsearch.properties

- name: copy the graph.properties
  template: src=learning/graph.properties.j2 dest=/data/properties/learning/graph.properties

- name: copy the mongo.properties
  template: src=learning/mongo.properties.j2 dest=/data/properties/learning/mongo.properties


#------------------------------------------------------------------------------------
- name: copy the elasticsearch.properties
  template: src=search/elasticsearch.properties.j2 dest=/data/properties/search/elasticsearch.properties
#------------------------------------------------------------------------------------
- name: copy the artifacts files 
  copy: src=learning-service.war dest=/home/ec2-user/apache-tomcat-8.0.35/webapps

- name: copy the artifacts files
  copy: src=search-service.war dest=/home/ec2-user/apache-tomcat-8.0.35/webapps

- name: copy the artifacts files
  copy: src=language-service.war dest=/home/ec2-user/apache-tomcat-8.0.35/webapps

- name: copy the artifacts file config-service.war
  copy: src=config-service.war dest=/home/ec2-user/apache-tomcat-8.0.35/webapps
#------------------------------------------------------------------------------------
- name: remove learning-service
  file: name=/home/ec2-user/apache-tomcat-8.0.35/webapps/learning-service state=absent

- name: remove search-service
  file: name=/home/ec2-user/apache-tomcat-8.0.35/webapps/search-service state=absent

- name: remove language-service
  file: name=/home/ec2-user/apache-tomcat-8.0.35/webapps/language-service state=absent

- name: remove config-service
  file: name=/home/ec2-user/apache-tomcat-8.0.35/webapps/config-service state=absent


- name: start tomcat
  service: name=tomcat state=started


