language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
services:
  - redis-server
before_install: 
  - source .travis/dependencies.sh
  - execute-dependencies
script:
  - mvn clean install