---
- name: copy setup script
  template: src=orchestrator_setup.j2 dest={{ user_home }}/orchestrator_setup.js

- name: run mongo script
  shell: mongo < {{ user_home }}/orchestrator_setup.js

- name: copy commands file
  template: src=commands.json.j2 dest={{ user_home }}/commands.json

- name: import orchestrator commands
  shell: mongoimport --db orchestrator_db --collection scripts --file {{ user_home }}/commands.json
