---
# tasks file for logstash
- name: Download th zip
  get_url: url=https://download.elastic.co/logstash/logstash/logstash-all-plugins-2.3.3.tar.gz dest=/home/ec2-user/logstash-all-plugins-2.3.3.tar.gz  timeout=1000 force=no owner=ec2-user 

- name: unzip 
  unarchive: src=/home/ec2-user/logstash-all-plugins-2.3.3.tar.gz dest=/home/ec2-user copy=no group=ec2-user owner=ec2-user creates=/home/ec2-user/logstash-2.3.3


- name: copy config file
  template: src=logstash-ekstep.j2 dest=/home/ec2-user/logstash-2.3.3/logstash-ekstep.conf

- name: set permissions
  become: yes
  file: path=/home/ec2-user/logstash-2.3.3 owner=ec2-user group=ec2-user mode=0755 recurse=yes 

- name: Run logstash
  shell: chdir=/home/ec2-user/logstash-2.3.3  bin/logstash -f /home/ec2-user/logstash-2.3.3/logstash-ekstep.conf -v &

 