version: 2.1
jobs:
  lp-build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: lp-dependency-cache-{{ checksum "pom.xml" }}
      - run: 
          name: Setup VM, Build and update Sonar
          command: bash vmsetup.sh

      - save_cache:
          key: lp-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2

      - run: mkdir temp && cp platform-modules/service/target/learning-service.war temp/
      - run: cp searchIndex-platform/module/search-api/search-manager/target/search-manager-1.0-SNAPSHOT.jar temp/
      - run: cp platform-tools/spikes/sync-tool/target/sync-tool-0.0.1-SNAPSHOT.jar temp/

      - store_artifacts:
         path: temp
         destination: temp/
     
workflows:
  version: 2.1
  workflow:
    jobs:
      - lp-build
