- name: Complete backup
  become: yes
  file: path=/home/learning/neo4j-backup state=absent
  tags:
       - fullbackup

- name: create directory
  become: yes
  file: path={{item}} state=directory owner=learning group=learning recurse=yes
  with_items:
             - /home/learning/neo4j-backup
  tags:
       - fullbackup
       - incrementalbackup

- name: copy template of scripthell script to stop service
  become: yes
  template: src=backup_script.j2 dest=/home/learning/backup_script.sh  mode=777 owner=learning group=learning
  tags:
       - fullbackup
       - incrementalbackup

- name: run script
  become: yes
  become_user: learning
  command: "/home/learning/backup_script.sh"
  tags:
       - fullbackup
       - incrementalbackup

- name: COPY the copy_s3.sh 
  become: yes
  template: src=copy_s3.j2 dest=/home/learning/copy_s3.sh  mode=777 owner=learning group=learning
  tags:
       - fullbackup
       - incrementalbackup

- name: run script
  become: yes
  become_user: learning
  command: chdir="/home/learning" sh copy_s3.sh
  tags:
       - fullbackup
       - incrementalbackup
