---
# tasks file for logstash
- name: Download th zip
  get_url: url=https://download.elastic.co/logstash/logstash/logstash-all-plugins-2.3.3.tar.gz dest=/home/ec2-user/logstash-all-plugins-2.3.3.tar.gz  timeout=1000 force=no owner=ec2-user 

- name: unzip 
  unarchive: src=/home/ec2-user/logstash-all-plugins-2.3.3.tar.gz dest=/home/ec2-user copy=no group=ec2-user owner=ec2-user creates={{ logstash_home }}

- name: add logstash configuration files
  template: src={{ item.name }}  dest={{ item.destination }}
  with_items:
    - { name: 'logstash-graph-events.j2', destination: '{{ logstash_home }}/logstash-graph-events.conf' }
    - { name: 'language-graph-events.j2', destination: '{{ logstash_home }}/language-graph-events.conf' }

- name: set permissions
  file: path={{ logstash_home }} owner=ec2-user group=ec2-user mode=0755 recurse=yes 

- name: Check if logstash graph events is running
  become_user: ec2-user
  shell: ps -ef | grep logstash | grep logstash-graph-events.conf | grep -v grep | wc -l
  register: logstash_process


- name: Check if logstash language graph events is running
  become_user: ec2-user
  shell: ps -ef | grep logstash | grep language-graph-events.conf | grep -v grep | wc -l
  register: language_process

- name: Run logstash
  become_user: ec2-user
  become: yes
  shell: {{ logstash_home }}/bin/logstash -f {{ logstash_home }}/logstash-graph-events.conf -v &
  async: 60
  poll: 30
  when: "logstash_process.stdout == '0'"


- name: Run logstash language
  become_user: ec2-user
  become: yes
  shell: chdir={{ logstash_home }}  bin/logstash -f {{ logstash_home }}/language-graph-events.conf -v &
  async: 60
  poll: 30
  when: "language_process.stdout == '0'"
