
- name: Check if neo4j is running
  become: yes
  become_user: learning
  shell: ps -ef | grep {{neo4j_home}}  | grep -v grep | wc -l
  register: neo4j_process
  tags: 
       - learning
       - language
  

- name: Stop the neo4j
  become: yes
  become_user: learning
  command: chdir={{ neo4j_home }}/bin ./neo4j stop
  when: "neo4j_process.stdout != '0'"
  tags: 
       - learning
       - language

- name: Cleanup
  become: yes
  file: path={{ neo4j_home }}/data/databases/graph.db state=absent
  tags: 
       - learning
       - language
 
- name: create graph.db
  become: yes
  file: path={{ neo4j_home }}/data/databases/graph.db state=directory owner={{user}} group={{user}}
  tags: 
       - learning
       - language

- name: Download the  backup zip file 
  become: yes
  become_user: learning
  command: aws s3 cp {{neo4j_backup_url}}/{{graph_machine}}_{{instance}}_{{date}}.tar.gz home/learning/
  tags: 
       - learning
       - language


- name: Unarchieve 
  become: yes
  become_user: learning
  unarchive: src=home/learning/{{graph_machine}}_{{instance}}_{{date}}.tar.gz dest=home/learning/ copy=no group={{user}} owner={{user}} creates={{graph_machine}}_{{instance}}_{{date}}
  tags: 
       - learning
       - language


- name: copy all the graph files 
  become: yes
  become_user: learning
  shell: cp -r /home/learning/{{graph_machine}}_{{instance}}_{{date}}/* /home/learning/{{ neo4j_dir }}/neo4j-enterprise-3.0.4/data/databases/graph.db/
  tags: 
       - learning
       - language
