---
# tasks file for redis

- name: install softwares build-essential
  become: yes
  yum: name="@Development tools" state=present 
  tags:
       - redis


- name: download redis zipfile
  become_user: ec2-user
  become: yes
  get_url: url=http://download.redis.io/releases/redis-stable.tar.gz dest=/home/ec2-user/redis-stable.tar.gz timeout=50 force=no owner=ec2-user
  tags:
       - redi


- name: unzip 
  unarchive: src=/home/ec2-user/redis-stable.tar.gz dest=/home/ec2-user copy=no group=ec2-user owner=ec2-user creates={{ redis_home }}
  tags:
       - redis



- name: Change ownership of redis installation
  file: path={{ redis_home }} owner=ec2-user group=ec2-user state=directory recurse=yes
  tags:
       - redis


- name: redis conf
  lineinfile: dest={{ redis_home }}/redis.conf regexp='^dir ./' state=absent
  tags:
       - redis


- name: redis conf
  lineinfile: dest={{ redis_home }}/redis.conf insertafter='# Note that you must specify a directory here, not a file name.' line='dir /home/ec2-user/redis-stable/' state=present
  tags:
       - redis


- name: Go to the folder and run make
  command: chdir={{ redis_home }} make
  tags:
       - redis


- name: Check if redis is running
  shell: ps -ef | grep redis | grep -v grep | wc -l
  register: redis_process
  changed_when: false
  ignore_errors: true
  tags:
       - redis


- name: start redis
  become_user: ec2-user
  shell: nohup src/redis-server &
  args:
    chdir: /home/ec2-user/redis-stable/
  async: 60
  poll: 60
  when: "redis_process.stdout == '0'"
  tags:
       - redis

