---
# tasks file for redis

- name: install softwares build-essential
  become: yes
  yum: name="@Development tools" state=present 
  tags:
       - redis


- name: download redis zipfile
  become_user: ec2-user
  become: yes
  get_url: url=http://download.redis.io/releases/redis-stable.tar.gz dest=/home/ec2-user/redis-stable.tar.gz timeout=50 force=no owner=ec2-user
  tags:
       - redis


- name: unzip 
  unarchive: src=/home/ec2-user/redis-stable.tar.gz dest=/home/ec2-user copy=no group=ec2-user owner=ec2-user creates={{ redis_home }}
  tags:
       - redis



- name: Change ownership of redis installation
  file: path={{ redis_home }} owner=ec2-user group=ec2-user state=directory recurse=yes
  tags:
       - redis


- name: redis conf
  template: src=redis.conf.j2 dest=/home/ec2-user/redis-stable/redis.conf
  tags:
       - redis


- name: Go to the folder and run make
  command: chdir={{ redis_home }} make
  tags:
       - redis

- name: copy template
  template: src=stop_script.j2 dest={{ user_home }}/stop_script.sh
  tags:
       - redis

- name: run script
  shell: sh {{ user_home }}/stop_script.sh
  tags: 
       - redis

- name: start redis
  become_user: ec2-user
  shell: nohup src/redis-server &
  args:
    chdir: /home/ec2-user/redis-stable/
  async: 60
  poll: 60
  tags:
       - redis

