swagger: '2.0'
info:
  version: '2.0'
  title: Definitions
  description: >-
    The Definitions API of EkStep Learning Platform provides details of all
    definitions of all objectTypes supported by the Platform
  license:
    name: EkStep License
    url: 'http:www.EkStep.in'
securityDefinitions: {}
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Definitions
    description: Provides Details about All Definitions of the Platform
paths:
  /taxonomy/domain/definition:
    get:
      summary: Gets All Definitions
      description: >-
        This API returns all the definitions of all ObjectTypes supported by the
        EkStep Learning Platform
      tags:
        - Definitions
      operationId: definition.list
      produces:
        - application/json
      responses:
        '200':
          description: All Definitions Returned Successfully
          schema:
            type: object
            properties:
              id:
                type: string
                description: API Identifier
              ver:
                type: string
                description: API version information
              ts:
                type: string
                description: API execution timespan
              params:
                title: Response Parameter
                type: object
                properties:
                  resmsgid:
                    type: string
                    description: Response Message Id
                  msgid:
                    type: string
                    description: Message Id
                  err:
                    type: string
                    description: Error Code
                  status:
                    type: string
                    description: Response Status
                  errmsg:
                    type: string
                    description: Error Message
              responseCode:
                type: string
                description: API response code
              result:
                properties:
                  definition_nodes:
                    type: array
                    items:
                      properties:
                        identifier:
                          type: string
                          description: Identifier
                        objectType:
                          type: string
                          description: objectType
                        properties:
                          type: object
                          title: properties
                          properties:
                            required:
                              type: boolean
                              description: required
                            dataType:
                              type: string
                              description: dataType
                            propertyName:
                              type: string
                              description: propertyName
                            title:
                              type: string
                              description: title
                            description:
                              type: string
                              description: description
                            category:
                              type: string
                              description: catergory
                            displayProperty:
                              type: string
                              description: displayProperty
                            range:
                              type: string
                              description: range
                            defaultValue:
                              type: string
                              description: defaultValue
                            renderingHints:
                              type: string
                              description: renderingHints
                            indexed:
                              type: string
                              description: indexed
                            draft:
                              type: string
                              description: draft
                        inRelations:
                          type: array
                          items:
                            properties:
                              relationName:
                                type: string
                                description: relationName
                              objectTypes:
                                type: object
                                description: objectTypes
                              title:
                                type: string
                                description: title
                              description:
                                type: string
                                description: description
                              required:
                                type: boolean
                                description: required
                              renderingHints:
                                type: string
                                description: renderingHints
                        outRelations:
                          type: array
                          items:
                            properties:
                              relationName:
                                type: string
                                description: relationName
                              objectTypes:
                                type: object
                                description: objectTypes
                              title:
                                type: string
                                description: title
                              description:
                                type: string
                                description: description
                              required:
                                type: boolean
                                description: required
                              renderingHints:
                                type: string
                                description: renderingHints
                        systemTags:
                          type: array
                          items:
                            properties:
                              name:
                                type: string
                                description: name
                              description:
                                type: string
                                description: description
                        metadata:
                          properties:
                            lastUpdatedOn:
                              type: string
                              description: last update
        '400':
          description: >-
            Error While fetching for all definitions! | Error occurred while
            operation, mostly because of the input given by client, In general
            it is 'Client Exception'
          schema:
            title: Failure Response
            type: object
            properties:
              id:
                type: string
                description: API Identifier
              ver:
                type: string
                description: API version information
              ts:
                type: string
                description: API execution timespan
              params:
                title: Failed Response Parameter
                type: object
                properties:
                  resmsgid:
                    type: string
                    description: Response Message Id
                  msgid:
                    type: string
                    description: Message Id
                  err:
                    type: string
                    description: Error Code
                  status:
                    type: string
                    description: Response Status
                  errmsg:
                    type: string
                    description: Error Message
              responseCode:
                type: string
                description: responseCode
        '500':
          description: >-
            Error While fetching for all definitions! | Error occurred while
            operation, mostly because of erroneous condition on server, In
            general it is 'Server Exception' or 'Exception'
          schema:
            title: Failure Response
            type: object
            properties:
              id:
                type: string
                description: API Identifier
              ver:
                type: string
                description: API version information
              ts:
                type: string
                description: API execution timespan
              params:
                title: Failed Response Parameter
                type: object
                properties:
                  resmsgid:
                    type: string
                    description: Response Message Id
                  msgid:
                    type: string
                    description: Message Id
                  err:
                    type: string
                    description: Error Code
                  status:
                    type: string
                    description: Response Status
                  errmsg:
                    type: string
                    description: Error Message
              responseCode:
                type: string
                description: responseCode
      security: []
  '/taxonomy/domian/definition/{objectType}':
    get:
      summary: Gets Specific Definition
      description: >-
        This API returns specific definition,its properties and relations based
        on the specified object type
      tags:
        - Definitions
      operationId: definition.find
      produces:
        - application/json
      parameters:
        - name: objectType
          in: path
          required: true
          description: objectType
          type: string
      responses:
        '200':
          description: Definition of specified objectType Returned Successfully
          schema:
            type: object
            properties:
              id:
                type: string
                description: API Identifier
              ver:
                type: string
                description: API version information
              ts:
                type: string
                description: API execution timespan
              params:
                title: Response Parameter
                type: object
                properties:
                  resmsgid:
                    type: string
                    description: Response Message Id
                  msgid:
                    type: string
                    description: Message Id
                  err:
                    type: string
                    description: Error Code
                  status:
                    type: string
                    description: Response Status
                  errmsg:
                    type: string
                    description: Error Message
              responseCode:
                type: string
                description: API response code
              result:
                properties:
                  definition_node:
                    properties:
                      identifier:
                        type: string
                        description: Identifier
                      objectType:
                        type: string
                        description: objectType
                      properties:
                        type: object
                        title: properties
                        properties:
                          required:
                            type: boolean
                            description: required
                          dataType:
                            type: string
                            description: dataType
                          propertyName:
                            type: string
                            description: propertyName
                          title:
                            type: string
                            description: title
                          description:
                            type: string
                            description: description
                          category:
                            type: string
                            description: catergory
                          displayProperty:
                            type: string
                            description: displayProperty
                          range:
                            type: string
                            description: range
                          defaultValue:
                            type: string
                            description: defaultValue
                          renderingHints:
                            type: string
                            description: renderingHints
                          indexed:
                            type: string
                            description: indexed
                          draft:
                            type: string
                            description: draft
                      inRelations:
                        type: array
                        items:
                          properties:
                            relationName:
                              type: string
                              description: relationName
                            objectTypes:
                              type: object
                              description: objectTypes
                            title:
                              type: string
                              description: title
                            description:
                              type: string
                              description: description
                            required:
                              type: boolean
                              description: required
                            renderingHints:
                              type: string
                              description: renderingHints
                      outRelations:
                        type: array
                        items:
                          properties:
                            relationName:
                              type: string
                              description: relationName
                            objectTypes:
                              type: object
                              description: objectTypes
                            title:
                              type: string
                              description: title
                            description:
                              type: string
                              description: description
                            required:
                              type: boolean
                              description: required
                            renderingHints:
                              type: string
                              description: renderingHints
                      systemTags:
                        type: array
                        items:
                          properties:
                            name:
                              type: string
                              description: name
                            description:
                              type: string
                              description: description
                      metadata:
                        properties:
                          lastUpdatedOn:
                            type: string
                            description: last update
        '400':
          description: >-
            Error While fetching for definition of specified objectType! | Error
            occurred while operation, mostly because of the input given by
            client, In general it is 'Client Exception'
          schema:
            title: Failure Response
            type: object
            properties:
              id:
                type: string
                description: API Identifier
              ver:
                type: string
                description: API version information
              ts:
                type: string
                description: API execution timespan
              params:
                title: Failed Response Parameter
                type: object
                properties:
                  resmsgid:
                    type: string
                    description: Response Message Id
                  msgid:
                    type: string
                    description: Message Id
                  err:
                    type: string
                    description: Error Code
                  status:
                    type: string
                    description: Response Status
                  errmsg:
                    type: string
                    description: Error Message
              responseCode:
                type: string
                description: responseCode
        '500':
          description: >-
            Error While fetching for definition of specified objectType! | Error
            occurred while operation, mostly because of erroneous condition on
            server, In general it is 'Server Exception' or 'Exception'
          schema:
            title: Failure Response
            type: object
            properties:
              id:
                type: string
                description: API Identifier
              ver:
                type: string
                description: API version information
              ts:
                type: string
                description: API execution timespan
              params:
                title: Failed Response Parameter
                type: object
                properties:
                  resmsgid:
                    type: string
                    description: Response Message Id
                  msgid:
                    type: string
                    description: Message Id
                  err:
                    type: string
                    description: Error Code
                  status:
                    type: string
                    description: Response Status
                  errmsg:
                    type: string
                    description: Error Message
              responseCode:
                type: string
                description: responseCode
      security: []