- hosts: learning
  remote_user: ec2-user
  become: yes
  roles:
        - mongodb

- hosts: language
  remote_user: ec2-user
  become: yes
  roles:
        - mongodb

- hosts: search
  remote_user: ec2-user
  become: yes
  roles:
        - mongodb                    


- hosts: config
  remote_user: ec2-user
  become: yes
  roles:
        - mongodb   