- hosts: "{{remote}}"
  remote_user: learning
  roles:
        #- aws-login
        #- java
        - createpath
        #- tomcat
        #- ffmpeg
        #- imagemagick
        #- logstash
        #- search-service
        #- redis
        #- mongodb       