- hosts: hostlanguage
  gather_facts: no
  become: yes
  roles:
        - java
        - createpath
        - aws-login
        - tomcat
        - logstash

- hosts: hostlearning
  gather_facts: no
  become: yes
  roles:
        - java
        - createpath
        - aws-login
        - tomcat
        - ffmpeg
        - imagemagick
        - logstash  


- hosts: hostsearch
  gather_facts: no
  become: yes
  roles:
        - java
        - createpath
        - aws-login
        - tomcat
        - logstash

- hosts: hostconfig
  gather_facts: no
  become: yes
  roles:
        - java
        - createpath
        - aws-login
        - tomcat  
      
- hosts: hostredis
  gather_facts: no
  become: yes
  roles:
        - redis

- hosts: hostmongodb
  gather_facts: no
  become: yes
  roles:
        - mongodb

- hosts: hosttotal
  gather_facts: no
  become: yes
  roles:
        - java
        - createpath
        - aws-login
        - tomcat
        - ffmpeg
        - imagemagick
        - logstash 