- hosts: "{{remote}}"
  remote_user: learning
  roles:
        - java
        - createpath
        - tomcat
        - ffmpeg
        - imagemagick
        - logstash
        - search-service
        - redis
        - mongodb       