- hosts: learning
  remote_user: ec2-user
  become: yes
  pre_tasks:
            - name: create folder data
              become: yes
              file: path={{ item }} state=directory mode=0755
              with_items:
                         - /data
                         - /data/graphDB
                         - /data/logs
                         - /data/contentBundle
                         - /data/properties
                         - /data/properties/learning
    
            - name: Change ownership of data directory
              become: yes
              file: path=/data owner={{user}} group={{user}} state=directory recurse=yes
  roles:
#        - java
#        - aws-login
#        - tomcat
#        - ffmpeg
#        - imagemagick
        - logstash

- hosts: language
  remote_user: ec2-user
  become: yes
  pre_tasks:
            - name: create folder data
              become: yes
              file: path={{ item }} state=directory mode=0755
              with_items:
                         - /data
                         - /data/graphDB
                         - /data/logs
                         - /data/contentBundle
                         - /data/prsoperties
                         - /data/properties/language
    
            - name: Change ownership of data directory
              become: yes
              file: path=/data owner={{user}} group={{user}} state=directory recurse=yes
  roles:
        - java
        - aws-login
        - tomcat
        - logstash


- hosts: search
  remote_user: ec2-user
  become: yes
  pre_tasks:
            - name: create folder data
              become: yes
              file: path={{ item }} state=directory mode=0755
              with_items:
                         - /data
                         - /data/logs
                         - /data/contentBundle
                         - /data/properties
                         - /data/properties/search
    
            - name: Change ownership of data directory
              become: yes
              file: path=/data owner={{user}} group={{user}} state=directory recurse=yes
  roles:
        - java
        - aws-login
        - tomcat
        - logstash
                            

- hosts: config
  remote_user: ec2-user
  become: yes
  pre_tasks:
            - name: create folder data
              become: yes
              file: path={{ item }} state=directory mode=0755
              with_items:
                         - /data
                         - /data/logs
                         - /data/contentBundle
                         - /data/properties
                         - /data/properties/config
    
            - name: Change ownership of data directory
              become: yes
              file: path=/data owner={{user}} group={{user}} state=directory recurse=yes
  roles:
        - java
        - aws-login
        - tomcat  
        - logstash  



- hosts: total
  remote_user: ec2-user
  become: yes
  pre_tasks:
            - name: create folder data
              become: yes
              file: path={{ item }} state=directory mode=0755
              with_items:
                         - /data
                         - /data/logs
                         - /data/graphDB
                         - /data/contentBundle
                         - /data/properties
                         - /data/properties/config
                         - /data/properties/search
                         - /data/properties/language
                         - /data/properties/language
                         - /data/properties/learning
  roles:
        - java
        - aws-login
        - tomcat
        - ffmpeg
        - imagemagick
        - logstash
    
    

- hosts: redis
  remote_user: ec2-user
  become: yes
  roles:
        - redis


- hosts: mongodb
  remote_user: ec2-user
  become: yes
  roles:
        - mongodb




