- hosts: learning
  remote_user: ec2-user
  become: yes
  roles:
        - redis

- hosts: language
  remote_user: ec2-user
  become: yes
  roles:
        - redis

- hosts: search
  remote_user: ec2-user
  become: yes
  roles:
        - redis                    

- hosts: config
  remote_user: ec2-user
  become: yes
  roles:
        - redis   