---
- name: stop tomcat
  become: yes
  service: name=tomcat state=stopped

- name: install neo4j
  get_url: url=http://dist.neo4j.org/neo4j-community-3.0.4-unix.tar.gz dest={{ user_home }}/neo4j-community-3.0.4-unix.tar.gz timeout=1000 force=no owner=ec2-user

- name: Unarchive neo4j
  unarchive: src={{ user_home }}/neo4j-community-3.0.4-unix.tar.gz dest={{ user_home }} copy=no   owner=ec2-user group=ec2-user creates={{ neo4j_home }}

- name: Backup
  file: path={{ user_home }}/backups mode=755 owner=ec2-user group=ec2-user state=directory

- name: Backup
  command: cp -r /data/graphDB/ {{ user_home }}/backups/

- name: Replace Working directory line
  lineinfile: dest={{ neo4j_home }}/conf/neo4j.conf regexp='dbms.allow_format_migration=true' insertafter='^#dbms.allow_format_migration=true' line='dbms.allow_format_migration=true' state=present


- name: copy template
  template: src=neo4j_script.j2 dest={{ user_home }}/neo4j_script.sh

- name: run script
  shell: sh {{ user_home }}/neo4j_script.sh


- name: start tomcat
  become: yes
  service: name=tomcat state=started
  
- name: Replace Working directory line
  lineinfile: dest={{ neo4j_home }}/conf/neo4j.conf regexp='dbms.allow_format_migration=true' insertafter='^dbms.allow_format_migration=true' line='#dbms.allow_format_migration=true' state=present










