- name: Copy DB script
  become: yes
  template:
    src: "data.cql.j2"
    dest: "/tmp/lp-data.cql"
    mode: 0755
  
- name: run cql 
  become: yes
  raw: /bin/bash -c 'CQLSH_NO_BUNDLED=true {{cql_path}} -f /tmp/lp-data.cql'