- name: create folder data for learning
  become: yes
  file: path={{ item }} state=directory mode=0755
  with_items:
     - /data
     - /data/graphDB
     - /data/logs
     - /data/contentBundle
     - /data/properties
     - /data/properties/learning
     - /home/{{user}}/tmp
     - /home/learning/platform
  tags:
        - learning
        - total

- name: create folder data
  become: yes
  file: path={{ item }} state=directory mode=0755
  with_items:
     - /data
     - /data/graphDB
     - /data/logs
     - /data/contentBundle
     - /data/properties
     - /data/properties/language
     - /home/{{user}}/tmp
     - /home/learning/platform
  tags:
       - language
       - total

- name: create folder data
  become: yes
  file: path={{ item }} state=directory mode=0755
  with_items:
     - /data
     - /data/logs
     - /data/contentBundle
     - /data/properties
     - /data/properties/search
     - /home/{{user}}/tmp
     - /home/learning/platform
     - /home/learning/platform/search
     - /home/learning/platform/service
     - /home/learning/platform/service/logs
  tags:
       - search
       - total

- name: create folder data
  become: yes
  file: path={{ item }} state=directory mode=0755
  with_items:
     - /data
     - /data/logs
     - /data/contentBundle
     - /data/properties
     - /data/properties/config
     - /home/{{user}}/tmp
     - /home/learning/platform
  tags:
       - config
       - total


- name: Change ownership of platform directory
  become: yes
  file: path=/home/{{user}}/platform owner={{user}} group={{user}}  recurse=yes
  tags:
       - learning
       - language
       - config
       - search


- name: Change ownership of tmp directory
  become: yes
  file: path=/home/{{user}}/tmp owner={{user}} group={{user}}  recurse=yes
  tags:
       - learning
       - language
       - config
       - search

- name: Change ownership of data directory
  become: yes
  file: path=/data owner={{user}} group={{user}}  recurse=yes
  tags:
       - learning
       - language
       - config
       - search

- include_vars: secrets/lp-secrets.yml
  tags:
       - always

- name: Add VisionKey.json key
  copy: content="{{ vision_key }}" dest={{user_home}}/platform/VisionKey.json mode=755 owner={{user}} group={{user}}
  tags:
       - always

- name: Update bashrc for VisionKey.json
  become: yes
  lineinfile: dest=/home/learning/.bashrc line='export GOOGLE_APPLICATION_CREDENTIALS=/home/learning/platform/VisionKey.json'  state=present insertafter=EOF create=yes
  tags:
       - always
