- name: create folder data for learning
  become: yes
  file: path={{ item }} state=directory mode=0755
  with_items:
     - /data
     - /data/graphDB
     - /data/logs
     - /data/contentBundle
     - /data/properties
     - /data/properties/learning
     - /home/ec2-user/tmp
  tags:
       - learning

- name: create folder data 
  become: yes
  file: path={{ item }} state=directory mode=0755
  with_items:
     - /data
     - /data/graphDB
     - /data/logs
     - /data/contentBundle
     - /data/properties
     - /data/properties/language
     - /home/ec2-user/tmp
  tags:
       - language

- name: create folder data
  become: yes
  file: path={{ item }} state=directory mode=0755
  with_items:
     - /data
     - /data/logs
     - /data/contentBundle
     - /data/properties
     - /data/properties/search
     - /home/ec2-user/tmp
  tags:
       - search

- name: create folder data
  become: yes
  file: path={{ item }} state=directory mode=0755
  with_items:
     - /data
     - /data/logs
     - /data/contentBundle
     - /data/properties
     - /data/properties/config
     - /home/ec2-user/tmp
  tags:
       - config

- name: create folder data
  become: yes
  file: path={{ item }} state=directory mode=0755
  with_items:
     - /data
     - /data/graphDB
     - /data/logs
     - /data/contentBundle
     - /data/properties
     - /data/properties/language
     - /data/properties/learning
     - /data/properties/search
     - /data/properties/config
     - /home/ec2-user/tmp
  tags:
       - total

- name: Change ownership of data directory
  become: yes
  file: path=/home/ec2-user/tmp owner=ec2-user group=ec2-user  recurse=yes
  tags:
       - learning
       - language
       - config
       - search

- name: Change ownership of data directory
  become: yes
  file: path=/data owner=ec2-user group=ec2-user  recurse=yes
  tags:
       - learning
       - language
       - config
       - search