---
- name: Debian | Add keys authenticity
  become: yes
  apt_key: url={{ url_apt_key }}0x7F0CEB10
  tags:
       - mongodb
       
- name: Debian | Add source sources
  become: yes
  apt_repository: repo='{{ mongodb_repository }}' update_cache=yes
  tags:
       - mongodb

- name: Debian | Install Packages
  become: yes
  apt: pkg={{ item }} state=installed
  with_items: mongodb-org
  tags:
       - mongodb

- name: copy setup mongod.conf
  become: yes
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  tags:
       - mongodb

- name: mongodb start
  become: yes
  service: name=mongod state=started
  tags:
       - mongodb
  
- name: copy setup script
  become: yes
  become_user: learning
  template: src=orchestrator_setup.j2 dest={{ user_home }}/orchestrator_setup.js
  tags:
       - mongodb

- name: run mongo script
  shell: mongo < {{ user_home }}/orchestrator_setup.js 
  tags:
       - mongodb
