---
#tasks file for deployartifact
- name: stop tomcat
  become: yes
  become_user: learning
  service: name=tomcat state=stopped
  tags:
       - learning
       - language
       - config
       - total

- name: Status of the search service
  become: yes
  become_user: learning
  command: "{{ service_path }}/search-service status"
  register: search_status
  tags:
       - search
       - total
  
- name: Stop the api service
  become: yes
  become_user: learning
  command: "{{ service_path }}/search-service stop"
  when: "search_status.stdout.find('RUNNING') != -1"
  async: 10
  poll: 5
  tags:
       - search
       - total
  

- name: copy the database.properties
  become: yes
  become_user: learning
  template: src=language/database.properties.j2 dest=/data/properties/language/database.properties
  tags:
       - language
       - total

- name: copy the elasticsearch.properties
  become: yes
  become_user: learning
  template: src=language/elasticsearch.properties.j2 dest=/data/properties/language/elasticsearch.properties
  tags:
       - language
       - total
 
- name: copy the graph.properties
  become: yes
  become_user: learning
  template: src=language/graph.properties.j2 dest=/data/properties/language/graph.properties
  tags:
       - language
       - total
 
- name: copy the language-indexes.properties
  become: yes
  become_user: learning
  template: src=language/language-indexes.properties.j2 dest=/data/properties/language/language-indexes.properties
  tags:
       - language
       - total
 

- name: copy the mongo.properties
  become: yes
  become_user: learning
  template: src=language/mongo.properties.j2 dest=/data/properties/language/mongo.properties
  tags:
       - language
       - total
 

- name: copy hibernate cofngi file
  become: yes
  become_user: learning
  template: src=language/hibernate.cfg.xml.j2 dest=/data/properties/language/hibernate.cfg.xml
  tags:
       - language
       - total
 

- name: copy the amazonS3Config.properties
  become: yes
  become_user: learning
  template: src=language/amazonS3Config.properties.j2 dest=/data/properties/language/amazonS3Config.properties
  tags:
       - language
       - total
 

#------------------------------------------------------------------------------------

- name: copy the consumer-config.xml
  become: yes
  become_user: learning
  template: src=learning/consumer-config.xml.j2 dest=/data/properties/learning/consumer-config.xml
  tags:
       - learning
       - total
 

- name: copy the database.properties
  become: yes
  become_user: learning
  template: src=learning/database.properties.j2 dest=/data/properties/learning/database.properties
  tags:
       - learning
       - total
 


- name: copy the elasticsearch.properties
  become: yes
  become_user: learning
  template: src=learning/elasticsearch.properties.j2 dest=/data/properties/learning/elasticsearch.properties
  tags:
       - learning
       - total


- name: copy the graph.properties
  become: yes
  become_user: learning
  template: src=learning/graph.properties.j2 dest=/data/properties/learning/graph.properties
  tags:
       - learning
       - total
 


- name: copy the mongo.properties
  become: yes
  become_user: learning
  template: src=learning/mongo.properties.j2 dest=/data/properties/learning/mongo.properties
  tags:
       - learning
       - total
 


- name: copy the content.properties
  become: yes
  become_user: learning
  template: src=learning/content.properties.j2 dest=/data/properties/learning/content.properties
  tags:
       - learning
       - total
 


- name: copy the amazonS3Config.properties
  become: yes
  become_user: learning
  template: src=learning/amazonS3Config.properties.j2 dest=/data/properties/learning/amazonS3Config.properties
  tags:
       - learning
       - total


- name: copy the cassandra.properties
  become: yes
  become_user: learning
  template: src=learning/cassandra.properties.j2 dest=/data/properties/learning/cassandra.properties
  tags:
       - learning
       - total
 


#------------------------------------------------------------------------------------
- name: copy the elasticsearch.properties
  become: yes
  become_user: learning
  template: src=search/elasticsearch.properties.j2 dest={{search_root}}/elasticsearch.properties
  tags:
       - search
       - total
 

#------------------------------------------------------------------------------------

- name: copy the amazonS3Config.properties
  become: yes
  become_user: learning
  template: src=config/amazonS3Config.properties.j2 dest=/data/properties/config/amazonS3Config.properties
  tags:
       - config
       - total
 

#------------------------------------------------------------------------------------

- name: copy the artifacts files 
  become: yes
  become_user: learning
  copy: src=learning-service.war dest=/home/{{user}}/apache-tomcat-8.0.36/webapps
  tags:
       - learning
       - total
 

- name: Copy search artifact
  become: yes
  become_user: learning
  copy: src=search-manager-1.0-SNAPSHOT-dist.zip dest={{ search_root }}
  tags:
       - search
       - total

 
- name: copy the artifacts files
  become: yes
  become_user: learning
  copy: src=language-service.war dest=/home/{{user}}/apache-tomcat-8.0.36/webapps
  tags:
       - language
       - total
 

- name: copy the artifacts file config-service.war
  become: yes
  become_user: learning
  copy: src=config-service.war dest=/home/{{user}}/apache-tomcat-8.0.36/webapps
  tags:
       - config
       - total
 

#------------------------------------------------------------------------------------
- name: remove learning-service
  become: yes
  become_user: learning
  file: name=/home/{{user}}/apache-tomcat-8.0.36/webapps/learning-service state=absent
  tags:
       - learning
       - total
 
- name: remove search-service
  become: yes
  become_user: learning
  file: name={{search_root}}/search-manager state=absent
  tags:
       - search
       - total
 

- name: remove language-service
  become: yes
  become_user: learning
  file: name=/home/{{user}}/apache-tomcat-8.0.36/webapps/language-service state=absent
  tags:
       - language
       - total
 

- name: remove config-service
  become: yes
  become_user: learning
  file: name=/home/{{user}}/apache-tomcat-8.0.36/webapps/config-service state=absent
  tags:
       - config
       - total
 

- name: start tomcat
  become: yes
  become_user: learning
  service: name=tomcat state=started
  tags:
       - learning
       - language
       - config
       - total

- name: wait for tomcat to start
  become: yes
  become_user: learning
  wait_for: port=8080
  tags:
       - learning
       - language
       - config
       - total
       
- name: Unarchive search artifact
  become: yes
  become_user: learning
  unarchive: src={{ search_root }}/search-manager-1.0-SNAPSHOT-dist.zip dest={{ search_root }} copy=no group={{ user }} owner={{ user }} mode=755
  tags: 
       - search
       - total

- name: Change search artifact
  become: yes
  become_user: learning
  command: mv /home/{{user}}/platform/search/search-manager-1.0-SNAPSHOT /home/{{user}}/platform/search/search-manager
  tags: 
       - search
       - total


- name: Start the search service
  become: yes
  become_user: learning
  command: "{{ service_path }}/search-service start"
  async: 20
  poll: 5 
  tags: 
       - search
       - total

- name: check language-service health
  shell: curl 'http://{{ service_url }}/language-service/health' | grep '"healthy":false' | wc -l
  register: language_process
  tags: 
       - language
       - total
 

#- name: check search-service health
#  shell: curl 'http://{{ service_url }}/search-service/health' | grep '"healthy":false' | wc -l
#  register: search_process
#  tags: 
#       - search
#       - total
 
- name: check learning-service health
  shell: curl 'http://{{ service_url }}/learning-service/health' | grep '"healthy":false' | wc -l
  register: learning_process
  tags: 
       - learning
       - total
 
        

- name: check config-service health
  shell: curl 'http://{{ service_url }}/config-service/health' | grep '"healthy":false' | wc -l
  register: config_process
  tags: 
       - config
       - total
 

- name: failed language-service health check
  fail: msg="Health check failed for language-service"
  when: "language_process.stdout >='1'"
  tags: 
       - language
       - total
 
       
# - name: failed search-service health check
#   fail: msg="Health check failed for search-service"
#   when: "search_process.stdout >= '1'"

- name: failed learning-service health check
  fail: msg="Health check failed for learning-service"
  when: "learning_process.stdout >= '1'"
  tags: 
       - learning
       - total
 

- name: failed config-service health check
  fail: msg="Health check failed for config-service"
  when: "config_process.stdout >= '1'"
  tags: 
       - config
       - total
 
