---
- name: copy template of shell script to Copy graphDB
  template: src=copy_graphdb_script.j2 dest=/home/{{user}}/copy_graphdb_script.sh owner={{user}} group={{user}} mode=0751
  
       
- name: run script
  become: yes  
  shell: nohup /home/{{user}}/copy_graphdb_script.sh "{{machine}}" &
  tags: 
       - always
