- hosts: lp-cassandra 
  # Install cassandra
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  roles:
    - jdk-1.8.0_121
    - cassandra-3.7.0
  tags: provision

- hosts: lp_cassandra
  become: yes
  # Create Schema
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  roles:
    - cassandra-db-update
  tags: deploy
