---
- hosts: zookeeper
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  pre_tasks:
    - service: name=monit state=stopped
      become: yes
      ignore_errors: true
  remote_user: "{{ ecosystem_user }}"
  become: yes
  roles:
    - java
    - zookeeper-upgrade
  post_tasks:
    - service: name=monit state=started
      become: yes
      ignore_errors: true
