- hosts: redisall
  become: yes
  become_user: "{{learner_user}}"
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ backup_azure_storage_access_key }}"
  roles:
   - redis-backup
  run_once: true
