
- name: Install required utils
  yum: name={{ item }} state=present 
  become: yes
  with_items:
    - git
    - git-core
    - zip
    - gcc
  tags:
       - learning

    
- name: Git clone FFmpeg repo
  git: repo=https://github.com/FFmpeg/FFmpeg.git dest=/home/ec2-user/ffmpeg version=release/3.0 
  tags:
       - learning


- name: change the permissions of ffmpeg
  file: path=/home/ec2-user/ffmpeg owner=ec2-user group=ec2-user recurse=yes
  tags:
       - learning


- name: run the command ./configure
  become: yes
  command: chdir=/home/ec2-user/ffmpeg  ./configure --disable-yasm
  tags:
       - learning

       
- name: run the command make
  become: yes
  command: chdir=/home/ec2-user/ffmpeg  make
  tags:
       - learning


- name: run the command make install
  become: yes
  command: chdir=/home/ec2-user/ffmpeg make install
  tags:
       - learning


- name: move ffmpeg files
  become: yes
  command: cp {{ user_home }}/ffmpeg/{{ item }} /usr/local/bin
  with_items:
             - ffmpeg
             - ffprobe
             - ffserver
  tags:
       - learning

  
- name: Change permissions after copying ffmpeg files
  become: yes
  file: path=/usr/local/bin/{{ item }} owner=ec2-user group=ec2-user mode=0755
  with_items:
     - ffmpeg
     - ffprobe
     - ffserver
  tags:
       - learning


