- name: Install required utils
  apt: name={{ item }} state=present 
  become: yes
  with_items:
    - git
    - git-core
    - zip
    - gcc
    - make
   # - make-guile
  tags:
       - learning
       - total

    
- name: Git clone FFmpeg repo
  become: yes
  become_user: learning
  git: repo=https://github.com/FFmpeg/FFmpeg.git dest=/home/{{user}}/ffmpeg version=release/3.0 
  tags:
       - learning
       - total


- name: change the permissions of ffmpeg
  become: yes
  become_user: learning
  file: path=/home/{{user}}/ffmpeg owner={{user}} group={{user}} recurse=yes
  tags:
       - learning
       - total


- name: run the command ./configure
  become: yes
  become_user: learning
  command: chdir=/home/{{user}}/ffmpeg  ./configure --disable-yasm
  tags:
       - learning
       - total

       
- name: run the command make
  become: yes
  become_user: learning
  command: chdir=/home/{{user}}/ffmpeg  make
  tags:
       - learning
       - total


- name: run the command make install
  become: yes
  command: chdir=/home/{{user}}/ffmpeg make install
  tags:
       - learning
       - total

- name: move ffmpeg files
  become: yes
  command: cp {{ user_home }}/ffmpeg/{{ item }} /usr/local/bin
  with_items:
             - ffmpeg
             - ffprobe
             - ffserver
  tags:
       - learning
       - total
  
- name: Change permissions after copying ffmpeg files
  become: yes
  file: path=/usr/local/bin/{{ item }} owner={{user}} group={{user}} mode=0755
  with_items:
     - ffmpeg
     - ffprobe
     - ffserver
  tags:
       - learning
       - total
