- name: Download
  become_user: ec2-user
  become: yes
  get_url: url=http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz dest=/home/ec2-user timeout=1000 force=no owner=ec2-user

- name: unzip 
  unarchive: src=/home/ec2-user/ffmpeg*  dest=/home/ec2-user copy=no group=ec2-user owner=ec2-user creates=ffmpeg-home

- name: Change ownership of ffmpeg installation
  become: yes
  file: path={{ ffmpeg_home }} owner=ec2-user group=ec2-user mode=755 state=directory recurse=yes  

- name: move files
  become: yes
  command: cp /home/ec2-user/ffmpeg-2.8/{{ item }} /usr/local/bin
  with_items:
             - ffmpeg
             - ffprobe
             - ffserver

- name: move files
  become: yes
  file: path=/usr/local/bin/{{ item }} owner=ec2-user group=ec2-user mode=0755
  with_items:
     - ffmpeg
     - ffprobe
     - ffserver
