- name: copy the jar file to cassandra trigger path
  copy:
    src: {{ item }}
    dest: /etc/cassandra/triggers
    with_fileglob:
      - static-files/cassandra.transaction-event-handler-*.jar

- name: copy logback.xml file to cassandra trigger path
  template:
    src: "logback.j2"
    dest: "/etc/cassandra/triggers/logback.xml"
    mode: 0755

- name: restart the cassandra
  service:
    name: "cassandra"
    state: "restarted"