- name: ensure templates and mapping dir exists
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ templates_dir }}"
    - "{{ mapping_dir }}"

- name: Copy templates file
  copy: src="files/templates/{{ item }}.json" dest="{{ templates_dir }}"
  with_items: "{{ template_name.split(',')|list }}"
  when: ansible_tag == 'run_single_index_and_mapping'

- name: Copy mapping file
  copy: src="files/mappings/{{ item }}-mapping.json" dest="{{ mapping_dir }}"
  with_items: "{{ mapping_name.split(',')|list }}"
  when: ansible_tag == 'run_single_index_and_mapping'

- name: Copy template file
  copy: src="files/templates/" dest="{{ templates_dir }}"
  when: ansible_tag == 'run_all_index_and_mapping'

- name: Copy mapping file
  copy: src="files/mappings/" dest="{{ mapping_dir }}"
  when: ansible_tag == 'run_all_index_and_mapping'

- name: copy es-mapping script
  template:
    src: elasticsearch_mapping.j2
    dest: /tmp/elasticsearch_mapping.sh
    mode: 0744

- name: running the script to create indices and mappings
  command: /tmp/elasticsearch_mapping.sh
  register: out
 
- debug: var=out.stdout_lines

- name: remove templates and mapping dir 
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ templates_dir }}"
    - "{{ mapping_dir }}"
